FROM sonarqube

RUN cd /opt/sonarqube/extensions/plugins && wget https://ci.appveyor.com/api/buildjobs/ipja13b5n0ibjn3p/artifacts/sonar-c-plugin%2Ftarget%2Fsonar-c-plugin-1.3.0.1677.jar 
RUN cd /opt/sonarqube/extensions/plugins && wget https://ci.appveyor.com/api/buildjobs/ipja13b5n0ibjn3p/artifacts/sonar-cxx-plugin%2Ftarget%2Fsonar-cxx-plugin-1.3.0.1677.jar
#RUN cd /opt/sonarqube/extensions/plugins && wget https://github.com/SonarOpenCommunity/sonar-cxx/releases/download/cxx-1.2.2/sslr-cxx-toolkit-1.2.2.1653.j




