version: '3.1'
services:
     jenkins:
        build: master
        ports:
            - '8080:8080'
            - '50000:50000'

     slave:
        build: slave
        restart: always
        environment:
            - 'JENKINS_URL=http://jenkins:8080'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - jenkins

     sonarqube:
        build: sonarqube
        ports:
           - '9000:9000'
        restart: always
        depends_on:
            - jenkins 
  
     artifactory:
        image: docker.bintray.io/jfrog/artifactory-oss:latest
        ports:
           - '8081:8081'
        #volumes:
        #- /data/artifactory:/var/opt/jfrog/artifactory
        depends_on:
            - jenkins
#    Add extra Java options by uncommenting the following lines
#    environment:
#     - EXTRA_JAVA_OPTIONS=-Xmx4g
        restart: always
        ulimits:
          nproc: 65535
          nofile:
              soft: 32000
              hard: 40000
